from os import environ as env


API_KEY = env.get('TWITTER_API_KEY')
API_SECRET_KEY = env.get('TWITTER_API_SECRET_KEY')
ACCESS_TOKEN = env.get('TWITTER_ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = env.get('TWITTER_ACCESS_TOKEN_SECRET')
BEARER_TOKEN = env.get('TWITTER_BEARER_TOKEN')
